# E*TRADE Account Configuration Template
# Copy this file to accounts.yaml and fill in your credentials

# API Credentials
api:
  consumer_key: "689c1faf762aa5a5eb6effaea98ece10"
  consumer_secret: "61e862eb03d31b4d1bbfb5ebdc7db76d48dcd5e010d71772ae26f581755d1545"
  sandbox: true  # Change to production environment

# Account Configurations
accounts:
  - id: "account1"
    account_number: "499 473826"
    description: "Individual Account"
    trading_enabled: true
    max_position_size: 50000  # Maximum position size in USD
    max_risk_per_trade: 0.01   # Maximum risk per trade (2% of account)
    strategies:
      - covered_calls
      - cash_secured_puts

  - id: "account2"
    account_number: "511 241903"
    description: "Traditional IRA"
    trading_enabled: true
    max_position_size: 100000
    max_risk_per_trade: 0.025
    strategies:
      - covered_calls

  - id: "account3"
    account_number: "511 791274"
    description: "Roth IRA"
    trading_enabled: true
    max_position_size: 100000
    max_risk_per_trade: 0.025
    strategies:
      - covered_calls

# Global Trading Parameters
trading:
  max_daily_trades: 10
  min_balance_required: 10000
  trading_hours:
    start: "09:30"  # Market open
    end: "16:00"    # Market close
  timezone: "America/New_York"

# Risk Management
risk_management:
  max_portfolio_risk: 0.15  # Maximum total portfolio risk
  max_sector_exposure: 0.25 # Maximum exposure to any single sector
  min_delta: 0.1           # Minimum option delta
  max_delta: 0.25           # Maximum option delta
  min_days_to_expiry: 7   # Minimum days until option expiration
  max_days_to_expiry: 30   # Maximum days until option expiration 